blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path('article', views.create_article, name='create_article'),
    path('author/<int:pk>', views.author, name='get_author'),
    path('article/<int:pk>', views.article, name='get_article'),
    path('', views.index, name='index')
]

main/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True)

    authors = models.ManyToManyField('Author')

    def __str__(self):
        return self.title

main/views.py
from django.shortcuts import render, get_object_or_404
from main import models

# Create your views here.
def index(request):
    latest_articles = models.Article.objects.all().order_by('-createdAt')[:10]
    context = {
        "latest_articles": latest_articles
    }
    return render(request, 'main/index.html', context)


def article(request, pk):
    article = get_object_or_404(models.Article, pk = pk)

    context = {
        'article': article
    }
    return render(request, 'main/article.html', context)


def author(request, pk):
    author = get_object_or_404(models.Author, pk = pk)

    context = {
        'author': author
    }
    return render(request, 'main/author.html', context)


def create_article(request):
    authors = models.Author.objects.all()

    context = {
        'authors': authors
    }

    if request.method == 'POST':
        article_data = {
            "title": request.POST['title'],
            "content": request.POST['content']
        }

        article = models.Article.objects.create(**article_data)
        author = models.Author.objects.filter(pk = request.POST['author'])
        article.authors.set(author)
        context['success'] = True


    return render(request, 'main/create_article.html', context)

templates/main/article.html
{% extends 'main/base.html' %}

{% block body %}
<h1>{{ article.title }}</h1>
<h3>Created At {{ article.createdAt }}</h3>
<h4>Written By: 
    {% for author in article.authors.all %}

        <a href="{% url 'get_author' author.id %}">{{ author }}</a>,
    {% endfor %}
</h4>
<p>{{ article.content }}</p>
{% endblock %}

templates/main/author.html
{% extends 'main/base.html' %}

{% block body %}
<h1> Name: {{ author.name }}</h1>
<h4> Articles Written: </h4>

<ul>
    {% for article in author.article_set.all %}
    <li>
        <a href="{% url 'get_article' article.id %}">{{ article.title }}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Application</title>
    <!-- <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="{% static 'js/materialize.min.js' %}"></script> -->
</head>
<body>
    {% block body %} {% endblock %}

    {% block script %} {% endblock %}
</body>
</html>

templates/main/create_article.html
{% extends 'main/base.html' %}

{% block body %}
<h1>Create an Article</h1>

{% if success %}

<p>Form Submitted</p>
{% endif %}

<form method="POST">
    {% csrf_token %}
    <input type="text" name="title" placeholder="Name" />
    <textarea name="content" placeholder="Content"></textarea>
    <select name="author">
        {% for author in authors %}
        <option value="{{ author.id }}">{{ author.name }}</option>
        {% endfor %}
    </select>
    <button type="submit">Submit</button>
    <button type="reset">Reset</button>
</form>
{% endblock %}

templates/main/index.html
{% extends 'main/base.html' %}

{% block body %}
<h1>Welcome</h1>
<h5>Top 10 Articles</h5>
<ul>
    {% for article in latest_articles %}
    <li>
        <a href="{% url 'get_article' article.id %}">{{ article }}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}